spring.application.name=demo3-pubsub
server.port=8083

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

spring.rabbitmq.listener.simple.acknowledge-mode=auto

logging.level.com.demo.pubsub=INFO
