spring.application.name=demo2-point-to-point
server.port=8082

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Manual acknowledge mode – consumer phải tự ack
spring.rabbitmq.listener.simple.acknowledge-mode=manual
# prefetch = 1 → fair dispatch, mỗi worker chỉ nhận 1 message tại 1 thời điểm
spring.rabbitmq.listener.simple.prefetch=1

logging.level.com.demo.p2p=INFO
